namespace PowerBasic.Compiler.Ir.Passes;

/// <summary>
/// O0332 — evaluates a sufficiently expensive pure one-byte function over all 256 input patterns and
/// replaces dynamic calls with indexed loads from a generated byte table. This is deliberately the
/// bit-exact integer subset; float tables wait for an evaluator with the runtime's exact FP semantics.
/// </summary>
public static class LookupTableGeneration {

  private const int _DOMAIN = 256;
  private const int _MIN_BODY_COST = 6;

  /// <summary>Generates profitable byte lookup tables; returns the number of functions tabled.</summary>
  public static int Run(IrModule module) {
    ArgumentNullException.ThrowIfNull(module);
    var generated = 0;
    foreach (var function in module.Functions.Where(function => !function.IsDeclaration).ToList())
      if (TryGenerate(module, function))
        ++generated;
    return generated;
  }

  private static bool TryGenerate(IrModule module, IrFunction function) {
    if (function.HasErrorHandler || function.HasInlineAsm || function.Parameters.Count != 1
        || !function.Parameters[0].Type.IsInteger || function.Parameters[0].Type.Bits != 8
        || !function.ReturnType.IsInteger || function.ReturnType.Bits != 8
        || function.Blocks.Count != 1 || function.Entry is not { } entry
        || entry.Instructions.Count(instruction => !instruction.IsTerminator) < _MIN_BODY_COST
        || entry.Terminator is not IrRet { HasValue: true } ret)
      return false;

    var calls = module.Functions
      .Where(caller => !caller.IsDeclaration && !caller.HasErrorHandler && !caller.HasInlineAsm)
      .SelectMany(caller => caller.AllInstructions.OfType<IrCall>())
      .Where(call => ReferenceEquals(call.Callee, function) && call.ArgCount == 1)
      .ToList();
    if (calls.Count < 2 || calls.All(call => call.Args.Single() is IrConstantInt))
      return false;                                  // a 256-byte table needs repeated dynamic use to pay rent

    var bytes = new byte[_DOMAIN];
    for (var input = 0; input < _DOMAIN; ++input) {
      if (!TryEvaluate(function, input, out var result))
        return false;
      bytes[input] = (byte)result;
    }

    var name = $".lut.{function.Name}";
    var table = module.FindGlobal(name);
    if (table is null) {
      table = module.AddGlobal(new IrGlobalVariable(name, IrType.I8) {
        Bytes = bytes,
        Count = _DOMAIN,
        IsZeroInitialized = false,
      });
    } else if (table.Bytes is null || !table.Bytes.SequenceEqual(bytes))
      return false;                                  // never silently reuse a same-named different object

    foreach (var call in calls) {
      var block = call.Parent;
      if (block is null)
        continue;
      var argument = call.Args.Single();
      IrValue index = argument is IrConstantInt constant
        ? new IrConstantInt(IrType.I16, (long)constant.ZeroExtended)
        : block.InsertBefore(new IrCast(IrCastOp.ZExt, argument, IrType.I16), call);
      var address = block.InsertBefore(new IrGep(table, index, IrType.I8), call);
      var load = block.InsertBefore(new IrLoad(call.Type, address), call);
      call.ReplaceAllUsesWith(load);
      call.EraseFromParent();
    }
    return true;
  }

  private static bool TryEvaluate(IrFunction function, long input, out long result) {
    result = 0;
    var values = new Dictionary<IrValue, long>(ReferenceEqualityComparer.Instance) {
      [function.Parameters[0]] = Wrap(function.Parameters[0].Type, input),
    };

    foreach (var instruction in function.Entry!.Instructions)
      switch (instruction) {
        case IrBinary binary when TryBinary(binary, values, out var binaryValue):
          values[binary] = binaryValue;
          break;
        case IrCmp compare when TryCompare(compare, values, out var comparison):
          values[compare] = comparison;
          break;
        case IrCast cast when TryCast(cast, values, out var castValue):
          values[cast] = castValue;
          break;
        case IrSelect select when ValueOf(select.Condition, values, out var condition)
                                  && ValueOf(condition != 0 ? select.IfTrue : select.IfFalse, values, out var selected):
          values[select] = Wrap(select.Type, selected);
          break;
        case IrRet { HasValue: true } ret when ValueOf(ret.Value!, values, out var returned):
          result = Wrap(function.ReturnType, returned);
          return true;
        default:
          return false;                              // load/store/call/phi/unknown op: not this pure subset
      }
    return false;
  }

  private static bool TryBinary(IrBinary binary, Dictionary<IrValue, long> values, out long result) {
    result = 0;
    if (!binary.Type.IsInteger || !ValueOf(binary.Lhs, values, out var left) || !ValueOf(binary.Rhs, values, out var right))
      return false;
    result = binary.Op switch {
      IrBinaryOp.Add => unchecked(left + right),
      IrBinaryOp.Sub => unchecked(left - right),
      IrBinaryOp.Mul => unchecked(left * right),
      IrBinaryOp.And => left & right,
      IrBinaryOp.Or => left | right,
      IrBinaryOp.Xor => left ^ right,
      _ => long.MinValue,
    };
    if (binary.Op is not (IrBinaryOp.Add or IrBinaryOp.Sub or IrBinaryOp.Mul or IrBinaryOp.And or IrBinaryOp.Or or IrBinaryOp.Xor))
      return false;
    result = Wrap(binary.Type, result);
    return true;
  }

  private static bool TryCompare(IrCmp compare, Dictionary<IrValue, long> values, out long result) {
    result = 0;
    if (!compare.Lhs.Type.IsInteger || !ValueOf(compare.Lhs, values, out var left)
        || !ValueOf(compare.Rhs, values, out var right))
      return false;
    var bits = compare.Lhs.Type.Bits;
    var unsignedLeft = Unsigned(bits, left);
    var unsignedRight = Unsigned(bits, right);
    var signedLeft = Signed(bits, left);
    var signedRight = Signed(bits, right);
    result = compare.Pred switch {
      IrCmpPred.Eq => unsignedLeft == unsignedRight ? 1 : 0,
      IrCmpPred.Ne => unsignedLeft != unsignedRight ? 1 : 0,
      IrCmpPred.Slt => signedLeft < signedRight ? 1 : 0,
      IrCmpPred.Sle => signedLeft <= signedRight ? 1 : 0,
      IrCmpPred.Sgt => signedLeft > signedRight ? 1 : 0,
      IrCmpPred.Sge => signedLeft >= signedRight ? 1 : 0,
      IrCmpPred.Ult => unsignedLeft < unsignedRight ? 1 : 0,
      IrCmpPred.Ule => unsignedLeft <= unsignedRight ? 1 : 0,
      IrCmpPred.Ugt => unsignedLeft > unsignedRight ? 1 : 0,
      IrCmpPred.Uge => unsignedLeft >= unsignedRight ? 1 : 0,
      _ => -1,
    };
    return result >= 0;
  }

  private static bool TryCast(IrCast cast, Dictionary<IrValue, long> values, out long result) {
    result = 0;
    if (!ValueOf(cast.Value, values, out var value) || !cast.Type.IsInteger || !cast.Value.Type.IsInteger)
      return false;
    result = cast.Op switch {
      IrCastOp.Trunc or IrCastOp.ZExt => Wrap(cast.Type, value),
      IrCastOp.SExt => Wrap(cast.Type, Signed(cast.Value.Type.Bits, value)),
      _ => long.MinValue,
    };
    return cast.Op is IrCastOp.Trunc or IrCastOp.ZExt or IrCastOp.SExt;
  }

  private static bool ValueOf(IrValue value, Dictionary<IrValue, long> values, out long result) {
    if (value is IrConstantInt constant) {
      result = Wrap(constant.Type, constant.Value);
      return true;
    }
    return values.TryGetValue(value, out result);
  }

  private static long Wrap(IrType type, long value)
    => type.Bits >= 64 ? value : unchecked((long)(unchecked((ulong)value) & ((1UL << type.Bits) - 1)));

  private static ulong Unsigned(int bits, long value)
    => bits >= 64 ? unchecked((ulong)value) : unchecked((ulong)value) & ((1UL << bits) - 1);

  private static long Signed(int bits, long value) {
    if (bits >= 64)
      return value;
    var pattern = Unsigned(bits, value);
    var sign = 1UL << (bits - 1);
    return unchecked((long)((pattern ^ sign) - sign));
  }
}
