using PowerBasic.Compiler.Ir.Analysis;

namespace PowerBasic.Compiler.Ir.Passes;

/// <summary>
/// O0332 — evaluates a sufficiently expensive pure integer function over a small proven input domain
/// and replaces repeated dynamic calls with indexed loads from a generated byte table. Evaluation is
/// deliberately bit-exact and integer-only; floating tables wait for exact runtime FP semantics.
/// </summary>
public static class LookupTableGeneration {

  private const int _MAX_DOMAIN = 256;
  private const int _MAX_PARAMETER_BITS = 16;
  private const int _MIN_BODY_COST = 6;
  private const int _MAX_EVAL_STEPS = 4096;

  private readonly record struct CallSite(IrFunction Caller, IrCall Call);

  private readonly record struct Domain(long Lo, long Hi, bool RawBytePatterns) {
    public int Count => this.RawBytePatterns ? _MAX_DOMAIN : checked((int)(this.Hi - this.Lo + 1));
  }

  /// <summary>Generates profitable byte lookup tables; returns the number of functions tabled.</summary>
  public static int Run(IrModule module) {
    ArgumentNullException.ThrowIfNull(module);
    var generated = 0;
    foreach (var function in module.Functions.Where(function => !function.IsDeclaration).ToList())
      if (TryGenerate(module, function))
        ++generated;
    return generated;
  }

  private static bool TryGenerate(IrModule module, IrFunction function) {
    if (function.HasErrorHandler || function.HasInlineAsm || function.Parameters.Count != 1
        || !SupportedInteger(function.Parameters[0].Type)
        || function.Parameters[0].Type.Bits > _MAX_PARAMETER_BITS
        || !function.ReturnType.IsInteger || function.ReturnType.Bits != 8
        || function.Entry is null
        || BodyCost(function) < _MIN_BODY_COST
        || function.Blocks.SelectMany(block => block.Instructions).Any(instruction => !Supported(instruction)))
      return false;

    var calls = module.Functions
      .Where(caller => !caller.IsDeclaration && !caller.HasErrorHandler && !caller.HasInlineAsm)
      .SelectMany(caller => caller.AllInstructions.OfType<IrCall>()
        .Where(call => ReferenceEquals(call.Callee, function) && call.ArgCount == 1)
        .Select(call => new CallSite(caller, call)))
      .ToList();
    var dynamicCalls = calls.Where(site => site.Call.Args.Single() is not IrConstantInt).ToList();
    if (dynamicCalls.Count < 2)
      return false;                                  // static data has to replace repeated runtime work, not a literal call

    if (!TryDomain(function.Parameters[0].Type, dynamicCalls, out var domain))
      return false;

    var bytes = new byte[domain.Count];
    for (var index = 0; index < domain.Count; ++index) {
      var input = domain.RawBytePatterns ? index : domain.Lo + index;
      if (!TryEvaluate(function, input, out var result))
        return false;                                // includes a path that traps, loops too long, or leaves the pure subset
      bytes[index] = (byte)result;
    }

    var name = TableName(function, domain);
    var table = module.FindGlobal(name);
    if (table is null) {
      table = module.AddGlobal(new IrGlobalVariable(name, function.ReturnType) {
        Bytes = bytes,
        Count = domain.Count,
        IsZeroInitialized = false,
      });
    } else if (!table.ValueType.SameStorage(function.ReturnType) || table.Count != domain.Count || table.IsZeroInitialized
               || table.Bytes is null || !table.Bytes.SequenceEqual(bytes))
      return false;                                  // never silently reuse a same-named object with a different layout/value

    foreach (var site in dynamicCalls) {
      var call = site.Call;
      var block = call.Parent;
      if (block is null)
        continue;
      var index = TableIndex(block, call, call.Args.Single(), function.Parameters[0].Type, domain);
      var address = block.InsertBefore(new IrGep(table, index, function.ReturnType), call);
      var load = block.InsertBefore(new IrLoad(call.Type, address), call);
      call.ReplaceAllUsesWith(load);
      call.EraseFromParent();
    }
    return true;
  }

  /// <summary>
  /// Finds one contiguous domain covering every dynamic call. Eight-bit parameters retain the old
  /// full-pattern fallback when a range cannot be interpreted consistently; wider parameters require
  /// an actual proof no larger than the table budget.
  /// </summary>
  private static bool TryDomain(IrType parameterType, IReadOnlyList<CallSite> calls, out Domain domain) {
    domain = default;
    var lo = long.MaxValue;
    var hi = long.MinValue;
    var analyses = new Dictionary<IrFunction, IrRangeAnalysis?>(ReferenceEqualityComparer.Instance);

    foreach (var site in calls) {
      var argument = site.Call.Args.Single();
      if (!argument.Type.SameStorage(parameterType) || argument.Type.Bits != parameterType.Bits)
        return false;

      // Same bits but a different signed interpretation can turn one mathematical interval into two
      // disjoint ranges. A complete byte-pattern table is still exact; a narrowed table is not.
      if (argument.Type.Bits > 1 && argument.Type.Signed != parameterType.Signed)
        return FullByteDomain(parameterType, out domain);

      if (site.Call.Parent is not { } block)
        return false;
      if (!analyses.TryGetValue(site.Caller, out var analysis)) {
        analysis = IrRangeAnalysis.Build(site.Caller);
        analyses[site.Caller] = analysis;
      }
      if (analysis is null)
        return FullByteDomain(parameterType, out domain);

      var range = analysis.RangeAt(argument, block);
      if (range.IsEmpty || range.IsTop)
        return FullByteDomain(parameterType, out domain);
      lo = Math.Min(lo, range.Lo);
      hi = Math.Max(hi, range.Hi);
    }

    var count = hi - lo + 1;
    if (count is <= 0 or > _MAX_DOMAIN)
      return FullByteDomain(parameterType, out domain);

    var whole = ValueRange.OfType(parameterType);
    domain = new Domain(lo, hi,
      parameterType.Bits == 8 && lo == whole.Lo && hi == whole.Hi);
    return true;
  }

  private static bool FullByteDomain(IrType parameterType, out Domain domain) {
    domain = default;
    if (parameterType.Bits != 8)
      return false;
    var whole = ValueRange.OfType(parameterType);
    domain = new Domain(whole.Lo, whole.Hi, RawBytePatterns: true);
    return true;
  }

  private static string TableName(IrFunction function, Domain domain) {
    var parameterType = function.Parameters[0].Type;
    if (domain.RawBytePatterns)
      return $".lut.{function.Name}";
    var startPattern = Unsigned(parameterType.Bits, domain.Lo);
    var sign = parameterType.Bits == 1 || parameterType.Signed ? 's' : 'u';
    return $".lut.{function.Name}.{sign}{parameterType.Bits}.{startPattern:x}.{domain.Count}";
  }

  private static IrValue TableIndex(IrBasicBlock block, IrCall call, IrValue argument,
      IrType parameterType, Domain domain) {
    if (domain.RawBytePatterns)
      return block.InsertBefore(new IrCast(IrCastOp.ZExt, argument, IrType.I16), call);

    IrValue index = argument;
    if (argument.Type.Bits < 16) {
      var op = argument.Type.Bits == 1 || !parameterType.Signed ? IrCastOp.ZExt : IrCastOp.SExt;
      index = block.InsertBefore(new IrCast(op, argument, IrType.I16), call);
    }
    if (domain.Lo != 0)
      index = block.InsertBefore(new IrBinary(IrBinaryOp.Sub, index, new IrConstantInt(index.Type, domain.Lo)), call);
    return index;
  }

  private static int BodyCost(IrFunction function)
    => function.Blocks.Sum(block => block.Instructions.Count(instruction => !instruction.IsTerminator && instruction is not IrPhi));

  private static bool Supported(IrInstruction instruction) => instruction switch {
    IrPhi phi => SupportedInteger(phi.Type),
    IrBinary binary => SupportedInteger(binary.Type) && binary.Op is
      IrBinaryOp.Add or IrBinaryOp.Sub or IrBinaryOp.Mul
      or IrBinaryOp.SDiv or IrBinaryOp.UDiv or IrBinaryOp.SRem or IrBinaryOp.URem
      or IrBinaryOp.And or IrBinaryOp.Or or IrBinaryOp.Xor
      or IrBinaryOp.Shl or IrBinaryOp.LShr or IrBinaryOp.AShr,
    IrCmp compare => SupportedInteger(compare.Lhs.Type) && SupportedInteger(compare.Rhs.Type)
      && compare.Pred is IrCmpPred.Eq or IrCmpPred.Ne
        or IrCmpPred.Slt or IrCmpPred.Sle or IrCmpPred.Sgt or IrCmpPred.Sge
        or IrCmpPred.Ult or IrCmpPred.Ule or IrCmpPred.Ugt or IrCmpPred.Uge,
    IrCast cast => SupportedInteger(cast.Type) && SupportedInteger(cast.Value.Type)
      && cast.Op is IrCastOp.Trunc or IrCastOp.ZExt or IrCastOp.SExt,
    IrSelect select => SupportedInteger(select.Type) && SupportedInteger(select.Condition.Type),
    IrBr => true,
    IrCondBr branch => SupportedInteger(branch.Condition.Type),
    IrSwitch @switch => SupportedInteger(@switch.Condition.Type),
    IrRet { HasValue: true } ret => SupportedInteger(ret.Value!.Type),
    _ => false,
  };

  private static bool SupportedInteger(IrType type) => type.IsInteger && type.Bits is >= 1 and <= 64;

  private static bool TryEvaluate(IrFunction function, long input, out long result) {
    result = 0;
    if (function.Entry is not { } block)
      return false;

    var values = new Dictionary<IrValue, long>(ReferenceEqualityComparer.Instance) {
      [function.Parameters[0]] = Wrap(function.Parameters[0].Type, input),
    };
    IrBasicBlock? predecessor = null;
    var steps = 0;

    while (steps < _MAX_EVAL_STEPS) {
      var incoming = new List<(IrPhi Phi, long Value)>();
      foreach (var phi in block.Instructions.OfType<IrPhi>()) {
        if (predecessor is null || phi.IncomingFrom(predecessor) is not { } value
            || !ValueOf(value, values, out var phiValue))
          return false;
        incoming.Add((phi, Wrap(phi.Type, phiValue)));
      }
      foreach (var (phi, value) in incoming)
        values[phi] = value;                         // simultaneous phi assignment, including loop backedges

      IrBasicBlock? next = null;
      foreach (var instruction in block.Instructions) {
        if (instruction is IrPhi)
          continue;
        if (++steps > _MAX_EVAL_STEPS)
          return false;

        switch (instruction) {
          case IrBinary binary when TryBinary(binary, values, out var binaryValue):
            values[binary] = binaryValue;
            break;
          case IrCmp compare when TryCompare(compare, values, out var comparison):
            values[compare] = comparison;
            break;
          case IrCast cast when TryCast(cast, values, out var castValue):
            values[cast] = castValue;
            break;
          case IrSelect select when ValueOf(select.Condition, values, out var condition)
                                    && ValueOf(condition != 0 ? select.IfTrue : select.IfFalse, values, out var selected):
            values[select] = Wrap(select.Type, selected);
            break;
          case IrBr branch:
            next = branch.Target;
            break;
          case IrCondBr branch when ValueOf(branch.Condition, values, out var condition):
            next = condition != 0 ? branch.IfTrue : branch.IfFalse;
            break;
          case IrSwitch @switch when ValueOf(@switch.Condition, values, out var condition):
            next = @switch.TargetFor(condition);
            break;
          case IrRet { HasValue: true } ret when ValueOf(ret.Value!, values, out var returned):
            result = Wrap(function.ReturnType, returned);
            return true;
          default:
            return false;
        }

        if (next is not null)
          break;
      }

      if (next is null)
        return false;
      predecessor = block;
      block = next;
    }
    return false;
  }

  private static bool TryBinary(IrBinary binary, Dictionary<IrValue, long> values, out long result) {
    result = 0;
    if (!SupportedInteger(binary.Type) || !ValueOf(binary.Lhs, values, out var left)
        || !ValueOf(binary.Rhs, values, out var right))
      return false;

    var bits = binary.Type.Bits;
    var shift = Unsigned(binary.Rhs.Type.Bits, right);
    switch (binary.Op) {
      case IrBinaryOp.Add: result = unchecked(left + right); break;
      case IrBinaryOp.Sub: result = unchecked(left - right); break;
      case IrBinaryOp.Mul: result = unchecked(left * right); break;
      case IrBinaryOp.And: result = left & right; break;
      case IrBinaryOp.Or: result = left | right; break;
      case IrBinaryOp.Xor: result = left ^ right; break;
      case IrBinaryOp.SDiv: {
        var divisor = Signed(bits, right);
        var dividend = Signed(bits, left);
        if (divisor == 0 || dividend == SignedMinimum(bits) && divisor == -1)
          return false;
        result = dividend / divisor;
        break;
      }
      case IrBinaryOp.SRem: {
        var divisor = Signed(bits, right);
        var dividend = Signed(bits, left);
        if (divisor == 0 || dividend == SignedMinimum(bits) && divisor == -1)
          return false;
        result = dividend % divisor;
        break;
      }
      case IrBinaryOp.UDiv: {
        var divisor = Unsigned(bits, right);
        if (divisor == 0)
          return false;
        result = unchecked((long)(Unsigned(bits, left) / divisor));
        break;
      }
      case IrBinaryOp.URem: {
        var divisor = Unsigned(bits, right);
        if (divisor == 0)
          return false;
        result = unchecked((long)(Unsigned(bits, left) % divisor));
        break;
      }
      case IrBinaryOp.Shl when shift < (ulong)bits:
        result = unchecked(left << (int)shift);
        break;
      case IrBinaryOp.LShr when shift < (ulong)bits:
        result = unchecked((long)(Unsigned(bits, left) >> (int)shift));
        break;
      case IrBinaryOp.AShr when shift < (ulong)bits:
        result = Signed(bits, left) >> (int)shift;
        break;
      default:
        return false;
    }

    result = Wrap(binary.Type, result);
    return true;
  }

  private static bool TryCompare(IrCmp compare, Dictionary<IrValue, long> values, out long result) {
    result = 0;
    if (!SupportedInteger(compare.Lhs.Type) || !ValueOf(compare.Lhs, values, out var left)
        || !ValueOf(compare.Rhs, values, out var right))
      return false;
    var bits = compare.Lhs.Type.Bits;
    var unsignedLeft = Unsigned(bits, left);
    var unsignedRight = Unsigned(bits, right);
    var signedLeft = Signed(bits, left);
    var signedRight = Signed(bits, right);
    result = compare.Pred switch {
      IrCmpPred.Eq => unsignedLeft == unsignedRight ? 1 : 0,
      IrCmpPred.Ne => unsignedLeft != unsignedRight ? 1 : 0,
      IrCmpPred.Slt => signedLeft < signedRight ? 1 : 0,
      IrCmpPred.Sle => signedLeft <= signedRight ? 1 : 0,
      IrCmpPred.Sgt => signedLeft > signedRight ? 1 : 0,
      IrCmpPred.Sge => signedLeft >= signedRight ? 1 : 0,
      IrCmpPred.Ult => unsignedLeft < unsignedRight ? 1 : 0,
      IrCmpPred.Ule => unsignedLeft <= unsignedRight ? 1 : 0,
      IrCmpPred.Ugt => unsignedLeft > unsignedRight ? 1 : 0,
      IrCmpPred.Uge => unsignedLeft >= unsignedRight ? 1 : 0,
      _ => -1,
    };
    return result >= 0;
  }

  private static bool TryCast(IrCast cast, Dictionary<IrValue, long> values, out long result) {
    result = 0;
    if (!ValueOf(cast.Value, values, out var value) || !SupportedInteger(cast.Type)
        || !SupportedInteger(cast.Value.Type))
      return false;
    result = cast.Op switch {
      IrCastOp.Trunc or IrCastOp.ZExt => Wrap(cast.Type, value),
      IrCastOp.SExt => Wrap(cast.Type, Signed(cast.Value.Type.Bits, value)),
      _ => long.MinValue,
    };
    return cast.Op is IrCastOp.Trunc or IrCastOp.ZExt or IrCastOp.SExt;
  }

  private static bool ValueOf(IrValue value, Dictionary<IrValue, long> values, out long result) {
    if (value is IrConstantInt constant) {
      result = Wrap(constant.Type, constant.Value);
      return true;
    }
    return values.TryGetValue(value, out result);
  }

  private static long Wrap(IrType type, long value)
    => type.Bits >= 64 ? value : unchecked((long)(unchecked((ulong)value) & ((1UL << type.Bits) - 1)));

  private static ulong Unsigned(int bits, long value)
    => bits >= 64 ? unchecked((ulong)value) : unchecked((ulong)value) & ((1UL << bits) - 1);

  private static long Signed(int bits, long value) {
    if (bits >= 64)
      return value;
    var pattern = Unsigned(bits, value);
    var sign = 1UL << (bits - 1);
    return unchecked((long)((pattern ^ sign) - sign));
  }

  private static long SignedMinimum(int bits) => bits >= 64 ? long.MinValue : -(1L << (bits - 1));
}
