#!/usr/bin/env bash
# Generates docs/DECOMPILATION.md: for every pb36 feature/optimization example under
# docs/decompilation/{features,optimizations}/*.bas, shows the original source next to its
# decompilation (pbc --emit-basic) with and without the optimizer, so the lowering of each
# feature - and what the optimizer does on top - is visible as readable PB 3.5.
#
# Each example .bas starts with metadata comments the generator reads:
#   ' @title: <short feature/optimization name>
#   ' @desc:  <one-line description of what to look for in the decompilation>
set -uo pipefail
cd "$(dirname "$0")/.."
PBC="$(find pbc/bin/Release -name pbc.dll 2>/dev/null | head -1)"
if [ -z "$PBC" ]; then dotnet build pbc -c Release -v q --nologo; PBC="$(find pbc/bin/Release -name pbc.dll 2>/dev/null | head -1)"; fi
run() { DOTNET_ROLL_FORWARD=Major dotnet "$PBC" "$@"; }
OUT="docs/DECOMPILATION.md"
TMP="${TMPDIR:-/tmp}/gendc.$$"; mkdir -p "$TMP"

meta() { sed -n "s/^' @$1:[[:space:]]*//p" "$2" | head -1; }
# the program body without the @-metadata header comments
body() { grep -vE "^' @(title|desc):" "$1"; }

emit_section() { # $1 = .bas file
  local f="$1" title desc
  title=$(meta title "$f"); [ -n "$title" ] || title=$(basename "$f" .bas)
  desc=$(meta desc "$f")
  echo "### $title"
  echo
  [ -n "$desc" ] && { echo "$desc"; echo; }

  echo "<details><summary>pb36 source</summary>"
  echo
  echo '```basic'
  body "$f"
  echo '```'
  echo "</details>"
  echo

  # decompilation without the optimizer (pure feature lowering)
  if run --dialect pb36 --no-optimize --emit-basic "$f" > "$TMP/no.bas" 2>"$TMP/err"; then
    : # ok
  else
    echo "> decompile (no-opt) failed:"; echo '```'; sed 's/^/  /' "$TMP/err"; echo '```'; echo; return
  fi
  # decompilation with the optimizer (lowering + OptPruner dead-code/DEF SEG cleanup)
  run --dialect pb36 --optimize --emit-basic "$f" > "$TMP/opt.bas" 2>/dev/null

  echo '**Decompiled (lowered to PB 3.5):**'
  echo
  echo '```basic'
  cat "$TMP/no.bas"
  echo '```'
  echo
  if diff -q "$TMP/no.bas" "$TMP/opt.bas" >/dev/null 2>&1; then
    echo '_With the optimizer: identical — this feature lowers entirely in the binder; the optimizer changes nothing at the source level._'
  else
    echo '**With the optimizer (`--optimize`, e.g. dead-code / `DEF SEG` cleanup):**'
    echo
    echo '```basic'
    cat "$TMP/opt.bas"
    echo '```'
  fi
  echo
}

{
  echo "# pb3.6 decompilation reference"
  echo
  echo "_Generated by \`scripts/gen-decompilation.sh\` — do not edit by hand; edit the examples under"
  echo "\`docs/decompilation/\` and regenerate._"
  echo
  echo "Each pb3.6 language feature and optimizer pass is shown as a minimal program next to its"
  echo "decompilation — \`pbc --dialect pb36 --emit-basic\`, which un-parses the bound program back to"
  echo "PB 3.5-compatible source. This reveals exactly what each feature lowers to (the binder's"
  echo "desugaring) and what the optimizer does on top of it. Constructs that lower below the source"
  echo "level (a real branch for the ternary, a state machine for \`YIELD\`, a thunk for a closure) are"
  echo "rendered in the nearest readable PB 3.5 form; their full machine lowering lives in the codegen."
  echo
  echo "> The optimizer column reflects the AST-level passes the back-emitter can see (dead-code"
  echo "> elimination, \`DEF SEG\` coalescing). Tier-2/3 optimizations (constant folding, CSE, the"
  echo "> peephole, the instruction scheduler, loop unrolling, inlining) operate below the source"
  echo "> level and are documented in docs/PIPELINE.md and docs/PB36.md."
  echo

  shopt -s nullglob
  if compgen -G "docs/decompilation/features/*.bas" >/dev/null; then
    echo "## Language features"
    echo
    for f in docs/decompilation/features/*.bas; do emit_section "$f"; done
  fi
  if compgen -G "docs/decompilation/optimizations/*.bas" >/dev/null; then
    echo "## Optimizations"
    echo
    echo "These are the optimizer passes whose effect is visible at the source level (the AST-level"
    echo "passes the back-emitter can render). Compile with \`--optimize\` (the pb36 default) vs"
    echo "\`--no-optimize\` to see the difference."
    echo
    for f in docs/decompilation/optimizations/*.bas; do emit_section "$f"; done
  fi

  cat <<'CATALOGUE'
## Optimizations below the source level

The bulk of the optimizer rewrites the *generated machine code*, not the AST, so it does not surface
in a source decompilation. For completeness, these passes run during code generation (see
docs/PIPELINE.md for the tier model and docs/PB36.md for the per-pass detail):

| Pass | Tier | What it does |
|------|------|--------------|
| Constant folding | 2 (emit) | folds compile-time-constant arithmetic / comparisons |
| Sparse conditional constant propagation (SCCP) | 1 (IR) | propagates constants through branches, prunes dead arms |
| Copy propagation | 2 (emit) | replaces a copy's uses with its source, killing the copy |
| Common-subexpression elimination (local + cross-block) | 2 (emit) | reuses an already-computed value instead of recomputing |
| Global value numbering (GVN) | 1 (IR) | unifies provably-equal computations |
| Dead-store elimination (DSE) | 1 (IR) | drops stores whose value is never read |
| Loop-invariant code motion (LICM) | 1 (IR) | hoists invariant work out of a loop |
| Induction-variable simplification | 2 (emit) | strength-reduces `i*const` loop addressing |
| Strength reduction | 2 (emit) | rewrites `x*const` as shift+add, `x\const` as a reciprocal/shift |
| Loop unrolling | 2 (emit) | unrolls small constant-trip loops |
| Inlining | 2 (emit) | inlines small/leaf procedures |
| Tail-call optimization | 2 (emit) | reuses the frame for a tail self-call (constant stack) |
| Dense `SELECT CASE` -> jump table | 2 (emit) | replaces the compare chain with an indexed indirect jump |
| Instruction scheduler | post-emit | reorders the final byte stream to group loads / ALU work (latency hiding) |
| Peephole | post-emit | local instruction-pattern rewrites (accumulator short forms, sign-extended imm8, ...) |
| Register-parameter passing | 1 (pre) | passes leaf-call arguments in registers |
| Float demotion | 1 (pre) | demotes a DOUBLE to SINGLE when the program never needs the precision |
| Reachability tree-shaking (O22) | 3 (layout) | drops unreachable procedures, runtime helpers and unread DATA |
| Runtime trim / virtual BSS / `.COM` | 3 (layout) | shrinks the image: unused runtime, zero-init data behind the image, tiny-model `.COM` |

CATALOGUE
} > "$OUT"

rm -rf "$TMP"
echo "wrote $OUT ($(wc -l < "$OUT") lines, $(ls docs/decompilation/features/*.bas docs/decompilation/optimizations/*.bas 2>/dev/null | wc -l) examples)"
