using System.Text;
using PowerBasic.Compiler.Syntax;

namespace PowerBasic.Compiler.Tests.Dialects;

/// <summary>
/// Runs the per-dialect battery and writes each dialect's README from what it measured.
///
/// The README is GENERATED, and the test fails when the file on disk disagrees with the measurement.
/// A hand-maintained checklist is accurate on the day it is written and silently stops being so; one
/// that is regenerated and compared cannot claim a dimension holds after the code stopped holding it.
/// </summary>
[TestFixture]
public sealed class DialectBatteryTests {

  private static readonly string _root = Path.GetFullPath(Path.Combine(
    TestContext.CurrentContext.TestDirectory, "..", "..", "..", ".."));

  internal static IEnumerable<Dialect> Dialects => DialectBattery.All;

  /// <summary>Every dimension for one dialect, in checklist order.</summary>
  private static IReadOnlyList<(DialectBattery.Dimension Dimension, DialectBattery.Measurement Measurement)>
    Measure(Dialect dialect) {
    var results = new List<(DialectBattery.Dimension, DialectBattery.Measurement)>();
    foreach (var dimension in DialectBattery.Dimensions)
      results.Add((dimension, dimension.Id switch {
        "syntax" => DialectProbes.Syntax(dialect),
        "lowering" => DialectProbes.Lowering(dialect),
        "foreign" => DialectProbes.Foreign(dialect),
        "dead-branch" => DialectProbes.DeadBranch(dialect),
        "live-branch" => DialectProbes.LiveBranch(dialect),
        "numeric-types" => DialectProbes.NumericTypes(dialect),
        "runtime-selection" => DialectProbes.RuntimeSelection(dialect),
        "runtime-behaviour" => DialectProbes.Unprobed(
          "every runtime entry in each variation, checked on stdout, written files and exit code"),
        "metastatements" => DialectProbes.Metastatements(dialect),
        "quirks" => DialectProbes.Quirks(dialect, _root),
        "bit-exact" => DialectProbes.BitExact(dialect),
        "readme" => new(DialectBattery.State.Held, 1, 1, "generated by this fixture"),
        _ => DialectProbes.Unprobed("no probe"),
      }));
    return results;
  }

  private static string Symbol(DialectBattery.State state) => state switch {
    DialectBattery.State.Held => "[x]",
    DialectBattery.State.Partial => "[~]",
    DialectBattery.State.NotApplicable => "[-]",
    _ => "[ ]",
  };

  private static string Readme(
    Dialect dialect,
    IReadOnlyList<(DialectBattery.Dimension D, DialectBattery.Measurement M)> results) {
    var held = results.Count(r => r.M.State is DialectBattery.State.Held or DialectBattery.State.NotApplicable);
    var text = new StringBuilder()
      .AppendLine($"# {dialect.DisplayName()} conformance battery")
      .AppendLine()
      .AppendLine("<!-- GENERATED by DialectBatteryTests. Edit the probes, not this file. -->")
      .AppendLine()
      .AppendLine($"`{dialect.CanonicalName()}` - family {dialect.Family()}, "
        + (dialect.IsInterpreter() ? "interpreted." : "compiled."))
      .AppendLine()
      .AppendLine($"**{held} of {results.Count} dimensions hold.** A box is ticked only when a probe runs and")
      .AppendLine("passes; an empty box means nobody has checked yet, which is not the same as failing.")
      .AppendLine()
      .AppendLine("| | Dimension | Measured | Notes |")
      .AppendLine("|---|---|---|---|");
    foreach (var (dimension, measurement) in results) {
      var measured = measurement.Total > 0 ? $"{measurement.Covered} / {measurement.Total}" : "-";
      text.AppendLine($"| {Symbol(measurement.State)} | {dimension.Title} | {measured} | {measurement.Note} |");
    }

    text.AppendLine()
      .AppendLine("## What each dimension claims")
      .AppendLine();
    foreach (var dimension in DialectBattery.Dimensions)
      text.AppendLine($"- **{dimension.Title}** - {dimension.Contract}");

    text.AppendLine()
      .AppendLine("## Legend")
      .AppendLine()
      .AppendLine("| Box | Meaning |")
      .AppendLine("|---|---|")
      .AppendLine("| `[x]` | A probe runs and every case passes. |")
      .AppendLine("| `[~]` | A probe runs and some cases do not pass yet; the note says how many. |")
      .AppendLine("| `[ ]` | No probe exists. Unverified, which is not the same as false. |")
      .AppendLine("| `[-]` | Cannot apply to this dialect. |");
    return text.ToString();
  }

  private static void WriteIfChanged(string path, string expected) {
    var normalized = expected.Replace("\r\n", "\n");
    if (!File.Exists(path) || File.ReadAllText(path).Replace("\r\n", "\n") != normalized)
      File.WriteAllText(path, expected);
  }

  [TestCaseSource(nameof(Dialects))]
  public void Battery_GivenADialect_ThenItsReadmeMatchesWhatTheProbesMeasure(Dialect dialect) {
    var results = Measure(dialect);
    var directory = Path.Combine(_root, DialectBattery.Directory(dialect).Replace('/', Path.DirectorySeparatorChar));
    Directory.CreateDirectory(directory);
    var path = Path.Combine(directory, "README.md");

    var expected = Readme(dialect, results);
    WriteIfChanged(path, expected);

    TestContext.Out.Write(expected);
    Assert.That(File.ReadAllText(path).Replace("\r\n", "\n"), Is.EqualTo(expected.Replace("\r\n", "\n")));
  }

  /// <summary>
  /// The index, so "where do we stand" is one table rather than nineteen files. Written by the same
  /// run that writes the per-dialect pages, from the same measurements.
  /// </summary>
  [Test]
  public void Battery_GivenEveryDialect_ThenTheIndexIsCurrent() {
    var text = new StringBuilder()
      .AppendLine("# Dialect conformance batteries")
      .AppendLine()
      .AppendLine("<!-- GENERATED by DialectBatteryTests. Edit the probes, not this file. -->")
      .AppendLine()
      .AppendLine("One battery per dialect. A dimension is ticked only where a probe runs and passes, so an")
      .AppendLine("empty column is work that is open rather than work that is done quietly.")
      .AppendLine();

    text.Append("| Dialect | Held |");
    foreach (var dimension in DialectBattery.Dimensions)
      text.Append(" " + dimension.Id + " |");
    text.AppendLine();
    text.Append("|---|---|");
    foreach (var unused in DialectBattery.Dimensions)
      text.Append("---|");
    text.AppendLine();

    foreach (var dialect in DialectBattery.All) {
      var results = Measure(dialect);
      var held = results.Count(r => r.Measurement.State is DialectBattery.State.Held or DialectBattery.State.NotApplicable);
      text.Append($"| [{dialect.CanonicalName()}]({dialect.CanonicalName()}/README.md) | {held}/{results.Count} |");
      foreach (var (_, measurement) in results)
        text.Append(" " + Symbol(measurement.State).Trim('[', ']', ' ').PadRight(1, '.') + " |");
      text.AppendLine();
    }

    var directory = Path.Combine(_root, "tests", "dialects");
    Directory.CreateDirectory(directory);
    var path = Path.Combine(directory, "README.md");
    var expected = text.ToString();
    WriteIfChanged(path, expected);

    TestContext.Out.Write(expected);
    Assert.That(File.ReadAllText(path).Replace("\r\n", "\n"), Is.EqualTo(expected.Replace("\r\n", "\n")));
  }
}
